import streamlit as st

from components import empty_state, metric_card, risk_table, status_badge
from theme import page_header, premium_divider, section_header, setup_page, sidebar
from utils import (
    available_columns,
    get_data_security_summary,
    get_insider_risk_summary,
    get_security_score,
    load_dashboard_data,
    load_unified_report,
    score_status,
)


def intelligence_summary(score: int, anomalies: int, high_risk_files: int, critical_users: int) -> str:
    posture = "strong security posture" if score >= 70 else "elevated security risk" if score < 40 else "security posture requiring attention"
    message = f"SecureScope reports a {posture}. {anomalies} anomalous events and {high_risk_files} high-risk files were identified."
    if critical_users:
        return f"{message} Immediate review is recommended for {critical_users} critical prioritized user event(s)."
    return f"{message} Continue validating the priority investigation queue against access policy."


setup_page()

try:
    with st.spinner("Loading unified intelligence report..."):
        report = load_unified_report()
        data = load_dashboard_data()
        data_security = get_data_security_summary()
        insider_risk = get_insider_risk_summary()
        security_score = get_security_score()
except FileNotFoundError as error:
    sidebar(active_page="Intelligence Center")
    empty_state("No unified intelligence report", str(error))
    st.stop()

sidebar(data.generated_at, active_page="Intelligence Center")
page_header(
    "Intelligence Center",
    "Executive intelligence synthesized from the latest unified data-security and insider-risk assessment.",
    data.generated_at,
)

status, tone = score_status(security_score)
section_header("Security posture", "A unified interpretation of data exposure and prioritized insider-risk signals.")
left, right = st.columns([2, 3])
with left:
    metric_card("Security score", f"{security_score} / 100", "Authoritative unified assessment", tone, "SCORE")
with right:
    status_badge(status, tone)
    st.markdown("#### Risk level")
    st.write(f"{100 - security_score}/100 organizational risk exposure")
    st.caption("Security score is generated by the unified intelligence pipeline; risk exposure is its inverse for executive context.")

premium_divider()
section_header("Data security intelligence", "Scanner results consolidated into the unified report.")
metrics = st.columns(4)
with metrics[0]:
    metric_card("Files scanned", data_security["files_scanned"], "Data sources assessed", "neutral", "SCAN")
with metrics[1]:
    metric_card("Sensitive findings", data_security["sensitive_findings"], "PII and secret detections", "warning", "FIND")
with metrics[2]:
    metric_card("High-risk files", data_security["high_risk_files"], "Require exposure review", "danger", "FILE")
with metrics[3]:
    metric_card("Critical exposures", data_security["critical_exposures"], "Files with critical findings", "danger", "CRIT")

premium_divider()
section_header("Insider-risk intelligence", "ML-informed priority events included by the unified report.")
metrics = st.columns(4)
with metrics[0]:
    metric_card("Events analyzed", insider_risk["events_analyzed"], "Activity records assessed", "neutral", "EVENT")
with metrics[1]:
    metric_card("Anomalies detected", insider_risk["anomalies_detected"], "Across all analyzed activity", "danger", "ANOM")
with metrics[2]:
    metric_card("Critical users", insider_risk["critical_users"], "In the prioritized event queue", "danger", "USER")
with metrics[3]:
    metric_card("Highest risk score", f"{insider_risk['highest_risk_score']}/100", "Within priority events", "warning", "RISK")

premium_divider()
section_header("Top risky users", "Priority events are sorted by risk score for rapid security-team triage.")
if data.risky_users.empty:
    empty_state("No priority users", "The current unified report does not contain insider-risk events.")
else:
    top_users = data.risky_users.sort_values("risk_score", ascending=False) if "risk_score" in data.risky_users else data.risky_users
    risk_table(top_users, available_columns(top_users, ["employee_id", "risk_score", "severity", "action", "location", "device"]))

premium_divider()
section_header("AI security summary", "Executive assessment based on the current unified-report signals.")
st.info(
    intelligence_summary(
        security_score,
        insider_risk["anomalies_detected"],
        data_security["high_risk_files"],
        insider_risk["critical_users"],
    )
)
st.caption(f"Assessment source: {report.get('project', 'SecureScope')} unified report.")
